### ISSUE TITLE
num peerps does not match max_ips

### ISSUE THREAD

**Issue by zxlin** [nicholaschiasson/ngx_upstream_jdomain#65]
Hey @nicholaschiasson, firstly thanks for the module here. 

I'm looking through the code, trying to understand the reason for this block of code below:

https://github.com/nicholaschiasson/ngx_upstream_jdomain/blob/bcf71ff90fd6acc200e3219340401b91f9b08a97/src/ngx_http_upstream_jdomain_module.c#L157-L160

What's the reason that peer pointers & `max_ips` have to be the same? What I'm seeing is that if an upstream server has 2 separate ports such as below:

```
upstream test {
  jdomain backend_1 port=1000 max_ips=2;
  jdomain backend_1 port=2000 max_ips=2;
}
```

Starting up nginx will trigger the `num peerps does not match max_ips` error message.

Changing the upstream to `max_ips=1` doesn't work either, e.g.

```
upstream test {
  jdomain backend_1 port=1000 max_ips=1;
  jdomain backend_1 port=2000 max_ips=1;
}
```

will also yield the same `num peerps does not match max_ips` error message.

Trying to understand if this is an intended design constraint or unintended behavior. I'm happy to contribute & help out if you'd like.

**Comment by nicholaschiasson** [comment]
Hi @zxlin,

I quickly looked into this. I have become somewhat unfamiliar with the code after a long break from this project, so I don't remember deeply the purpose for this check. There may have been more context when I wrote it. I should have written a comment or something. I suspect it was intended to just check that there were the correct number of array elements (`max_ips`) allocated for a given instance of the `jdomain` directive, otherwise assume something weird must have happened with the memory management... something unexpected in the upstream block such as an incompatible assortment of directives.

As it happens, in this case the check is actually useful in that it has revealed to us a nice bug! 😄 

It appears that the case of multiple `jdomain` directives with the same domain but different ports is unsupported. The for loop just before this check is looking for peers for which the server `name` matches the instance data's server `name`. This should work except that in the `ngx_http_upstream_jdomain` function I simply assigned the server `name` the value of the jdomain `domain` argument _without_ the port. So basically that loop will find more peers for `backend_1:1000` than expected since it's only checking that the name is `backend_1` and not `backend_1:1000`. It will increment `j` up to the sum of `max_ips` where the domain is `backend_1` and then result in writing out of bounds of `peerp`.

To fix this, the server `name` simply needs to have the port (to string) concatenated. I think that should be sufficient. And for this one I think to be safe, we'll need to allocate a new string buffer for the name with a size equal to the domain length plus the port string plus 1 for `:`. If you'd like to help out and submit a PR, that would be super awesome! Otherwise I can try to get around to the fix soon.

Thanks for reporting this!

**Comment by zxlin** [comment]
@nicholaschiasson I think the patch works in that it can start up fine now, but I don't think it's sending any traffic to another port of the same host. I'm testing with 2 hosts, 2 ports to each host as the upstream, only the first defined port of a host in the upstream block is receiving traffic.

e.g. 

```
  upstream test {
    ip_hash;
    jdomain test-1 port=8080 interval=60s max_ips=2;
    jdomain test-1 port=8081 interval=60s max_ips=2;
    jdomain test-2 port=8080 interval=60s max_ips=2;
    jdomain test-2 port=8081 interval=60s max_ips=2;
  }
```
only `test-1:8080` and `test-2:8080` are receiving traffic

**Comment by nicholaschiasson** [comment]
Hi @zxlin, could this be related to your use of ip_hash? Is this a small scale test you're conducting and is it possible due to the hashing function, we're never hitting the 8081 peers? If you're testing with a sufficient number of client IPs where that shouldn't be the case, then it's possible the module has a compatibility issue with ip_hash.

**Comment by zxlin** [comment]
I don't think it's `ip_hash`, I'm testing with 100 different client IPs.

I also tested changing the domain name to include a `.` at the end of one of the domain names, e.g. `test-1` and `test-1.` are both valid ways to represent the same domain name. In this test, clients are spread fairly evenly across the 4 upstreams. So it's unlikely that it's an issue with `ip_hash`. Config example below:
```
  upstream test {
    ip_hash;
    jdomain test-1 port=8080 interval=60s max_ips=2;
    jdomain test-1. port=8081 interval=60s max_ips=2;
    jdomain test-2 port=8080 interval=60s max_ips=2;
    jdomain test-2. port=8081 interval=60s max_ips=2;
  }
```
