### ISSUE TITLE
Jdomain support sockets?

### ISSUE THREAD

**Issue by lancergon** [nicholaschiasson/ngx_upstream_jdomain#79]
Hi,
I want to know if jdomain support the headers:

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";

or my config is wrong 

This is my nginx.config:
`
     load_module /usr/local/nginx/modules/objs/ngx_http_upstream_jdomain_module.so;
     user nginx;
     worker_processes auto;
     pid /run/nginx.pid;
     include /etc/nginx/modules-enabled/*.conf;
     events {
        worker_connections 1024;
        multi_accept on;
     }
    http {
       client_max_body_size 0;
       resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        server_name  http://proxy;
        proxy_connect_timeout 1200s;
        proxy_send_timeout 1200s;
        proxy_read_timeout 1200s;
        fastcgi_send_timeout 1200s;
        fastcgi_read_timeout 1200s;

        location ~ ^/(?!(api/)){
            set $test_arch_archivistica_ui http://test_arch_archivistica_ui:80;
            rewrite /(.*) /$1 break;
            proxy_pass $test_arch_archivistica_ui;
        }

        location /api/notifications_alert{
            rewrite /api/notifications_alert/(.*) /$1 break;
            set $test_notifications_alert test_notifications_alert;
            proxy_pass http://$test_arch_notifications_notifications_alert;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

    }

    upstream test_notifications_alert{
        server 127.0.0.2 backup;
        jdomain test_arch_notifications strict interval=10  port=3001;
    }

      server {
            listen 127.0.0.2:80;
            return 502 'An error.';
          }
   }
`
and the way I connect is:

`  
      var private_socket = io('192.168.0.227/private-alert', {path:"/test_arch/api/notifications_alert/socket.io"} );

       private_socket.on('connect', function(msg) {
           console.log('Usuario ${msg} conectado')
      });
`

the error that marks me is:
` 
   WebSocket connection to 'ws://192.168.0.227/test_arch/api/notifications_alert/socket.io/?EIO=3&transport=websocket' failed:
`

thanks in advance :D

**Comment by nicholaschiasson** [comment]
Hi @lancergon sorry for the late response. I am curious if you still have not figured it out. I wanted to ask if you had ever managed to have something working with this config but without jdomain entirely. I could be wrong but I spot some peculiarities with your config.

Firstly, you use `server_name http://proxy;` which has two problems. Firstly, you shouldn't include the protocol scheme in your `server_name` directive and secondly, I don't see you actually using a host header of `proxy` when you make your connection. So I don't believe that nginx will select this server block even if you connect to nginx on port 80.

The next thing I noticed has to do with your location blocks. It looks to me like the connection you're trying to establish maps to your second location block, but this location block is defined to have the prefix `/api/notifications_alert` while you're requesting `/test_arch/api/notifications_alert`. Forgive me if I'm missing some details here but it seems that location won't match.

What's more, even if your request was processed by that location block, I don't see how it would handle the request. I think you may have a typo in the configuration, as you define a variable `$test_notifications_alert`, but `proxy_pass` to a variable `$test_arch_notifications_notifications_alert` which is not defined anywhere else in the config you've included here.

I'm going to mark this issue closed since it's been open a long time without follow up (sorry again about that). Comment back if you have concerns or want it reopened.
